using System;

namespace Hinode.Izumi.Data.Enums.AchievementEnums
{
    public enum Achievement : byte
    {
        FirstMessage = 1,
        FirstTransit = 2,
        FirstFish = 3,
        FirstGatheringResource = 4,
        FirstPlant = 5,
        FirstCraftResource = 6,
        FirstCraftAlcohol = 60,
        FirstCook = 7,
        FirstBet = 8,
        FirstJackPot = 9,
        FirstLotteryTicket = 10,
        FirstMarketDeal = 11,
        FirstContract = 20,
        FirstGiftSent = 23,
        FirstGiftReceived = 24,
        Gather40Resources = 21,
        Gather250Resources = 22,
        Catch50Fish = 12,
        Catch300Fish = 13,
        CatchEpicFish = 25,
        CatchMythicalFish = 26,
        CatchLegendaryFish = 27,
        CatchKoi = 28,
        Plant25Seed = 14,
        Plant150Seed = 15,
        Collect50Crop = 63,
        Collect300Crop = 64,
        Cook20Food = 18,
        Cook130Food = 19,
        Craft30Resource = 16,
        Craft250Resource = 17,
        Craft10Alcohol = 61,
        Craft80Alcohol = 62,
        Casino33Bet = 65,
        Casino777Bet = 66,
        Casino22LotteryBuy = 67,
        Casino99LotteryBuy = 68,
        Casino20LotteryGift = 69,
        Market100Sell = 70,
        Market666Sell = 71,
        Market50Buy = 72,
        Market333Buy = 73,
        CompleteCollectionGathering = 54,
        CompleteCollectionCrafting = 55,
        CompleteCollectionAlcohol = 56,
        CompleteCollectionCrop = 57,
        CompleteCollectionFish = 58,
        CompleteCollectionFood = 59,
        CompleteCollectionDrink = 74,
        MeetSummer = 75
    }

    public static class AchievementHelper
    {
        public static string Localize(this Achievement achievement) => achievement switch
        {
            Achievement.FirstMessage => "Написать первое сообщение",
            Achievement.FirstTransit => "Впервые отправиться на транспорте",
            Achievement.FirstFish => "Выловить первую рыбу",
            Achievement.FirstGatheringResource => "Собрать свой первый ресурс",
            Achievement.FirstPlant => "Впервые посадить семена",
            Achievement.FirstCraftResource => "Впервые изготовить ресурс",
            Achievement.FirstCraftAlcohol => "Впервые изготовить алкоголь",
            Achievement.FirstCook => "Впервые приготовить блюдо",
            Achievement.FirstBet => "Впервые поставить монеты в казино",
            Achievement.FirstJackPot => "Впервые сорвать джек-пот в казино",
            Achievement.FirstLotteryTicket => "Купить свой первый лотерейный билет",
            Achievement.FirstMarketDeal => "Впервые купить или продать предмет на рынке",
            Achievement.FirstContract => "Выполнить свой первый рабочий контракт",
            Achievement.FirstGiftSent => "Впервые отправить подарок другому игроку",
            Achievement.FirstGiftReceived => "Впервые получить подарок от другого игрока",
            Achievement.Gather40Resources => "Собрать 40 ресурсов",
            Achievement.Gather250Resources => "Собрать 250 ресурсов",
            Achievement.Catch50Fish => "Выловить 50 рыб",
            Achievement.Catch300Fish => "Выловить 300 рыб",
            Achievement.CatchEpicFish => "Поймать эпическую рыбу",
            Achievement.CatchMythicalFish => "Поймать мифическую рыбу",
            Achievement.CatchLegendaryFish => "Поймать легендарную рыбу",
            Achievement.CatchKoi => "Выловить Кои",
            Achievement.Plant25Seed => "Посадить 25 семян",
            Achievement.Plant150Seed => "Посадить 150 семян",
            Achievement.Collect50Crop => "Собрать 50 урожая",
            Achievement.Collect300Crop => "Собрать 300 урожая",
            Achievement.Cook20Food => "Приготовить 20 блюд",
            Achievement.Cook130Food => "Приготовить 130 блюд",
            Achievement.Craft30Resource => "Изготовить 30 ресурсов",
            Achievement.Craft250Resource => "Изготовить 250 ресурсов",
            Achievement.Craft10Alcohol => "Изготовить 10 алкоголя",
            Achievement.Craft80Alcohol => "Изготовить 80 алкоголя",
            Achievement.Casino33Bet => "Сделать 33 ставки",
            Achievement.Casino777Bet => "Сделать 777 ставок",
            Achievement.Casino22LotteryBuy => "Купить 22 лотерейных билета",
            Achievement.Casino99LotteryBuy => "Купить 99 лотерейных билетов",
            Achievement.Casino20LotteryGift => "Подарить 20 лотерейных билетов",
            Achievement.Market100Sell => "Продать на рынке 100 предметов",
            Achievement.Market666Sell => "Продать на рынке 666 предметов",
            Achievement.Market50Buy => "Купить на рынке 50 предметов",
            Achievement.Market333Buy => "Купить на рынке 333 предмета",
            Achievement.CompleteCollectionGathering => "Собрать полную коллекцию ресурсов",
            Achievement.CompleteCollectionCrafting => "Собрать полную коллекцию изготовленных предметов",
            Achievement.CompleteCollectionAlcohol => "Собрать полную коллекцию алкоголя",
            Achievement.CompleteCollectionCrop => "Собрать полную коллекцию урожая",
            Achievement.CompleteCollectionFish => "Собрать полную коллекцию рыбы",
            Achievement.CompleteCollectionFood => "Собрать полную коллекцию блюд",
            Achievement.CompleteCollectionDrink => "Собрать полную коллекцию напитков",
            Achievement.MeetSummer => "Встретить лето",
            _ => throw new ArgumentOutOfRangeException(nameof(achievement), achievement, null)
        };

        public static AchievementCategory Category(this Achievement achievement) => achievement switch
        {
            Achievement.FirstMessage => AchievementCategory.FirstSteps,
            Achievement.FirstTransit => AchievementCategory.FirstSteps,
            Achievement.FirstFish => AchievementCategory.FirstSteps,
            Achievement.FirstGatheringResource => AchievementCategory.FirstSteps,
            Achievement.FirstPlant => AchievementCategory.FirstSteps,
            Achievement.FirstCraftResource => AchievementCategory.FirstSteps,
            Achievement.FirstCraftAlcohol => AchievementCategory.FirstSteps,
            Achievement.FirstCook => AchievementCategory.FirstSteps,
            Achievement.FirstBet => AchievementCategory.FirstSteps,
            Achievement.FirstJackPot => AchievementCategory.FirstSteps,
            Achievement.FirstLotteryTicket => AchievementCategory.FirstSteps,
            Achievement.FirstMarketDeal => AchievementCategory.FirstSteps,
            Achievement.FirstContract => AchievementCategory.FirstSteps,
            Achievement.FirstGiftSent => AchievementCategory.FirstSteps,
            Achievement.FirstGiftReceived => AchievementCategory.FirstSteps,
            Achievement.Gather40Resources => AchievementCategory.Gathering,
            Achievement.Gather250Resources => AchievementCategory.Gathering,
            Achievement.Catch50Fish => AchievementCategory.Fishing,
            Achievement.Catch300Fish => AchievementCategory.Fishing,
            Achievement.CatchEpicFish => AchievementCategory.Fishing,
            Achievement.CatchMythicalFish => AchievementCategory.Fishing,
            Achievement.CatchLegendaryFish => AchievementCategory.Fishing,
            Achievement.CatchKoi => AchievementCategory.Fishing,
            Achievement.Plant25Seed => AchievementCategory.Harvesting,
            Achievement.Plant150Seed => AchievementCategory.Harvesting,
            Achievement.Collect50Crop => AchievementCategory.Harvesting,
            Achievement.Collect300Crop => AchievementCategory.Harvesting,
            Achievement.Cook20Food => AchievementCategory.Cooking,
            Achievement.Cook130Food => AchievementCategory.Cooking,
            Achievement.Craft30Resource => AchievementCategory.Crafting,
            Achievement.Craft250Resource => AchievementCategory.Crafting,
            Achievement.Craft10Alcohol => AchievementCategory.Crafting,
            Achievement.Craft80Alcohol => AchievementCategory.Crafting,
            Achievement.Casino33Bet => AchievementCategory.Casino,
            Achievement.Casino777Bet => AchievementCategory.Casino,
            Achievement.Casino22LotteryBuy => AchievementCategory.Casino,
            Achievement.Casino99LotteryBuy => AchievementCategory.Casino,
            Achievement.Casino20LotteryGift => AchievementCategory.Casino,
            Achievement.Market100Sell => AchievementCategory.Trading,
            Achievement.Market666Sell => AchievementCategory.Trading,
            Achievement.Market50Buy => AchievementCategory.Trading,
            Achievement.Market333Buy => AchievementCategory.Trading,
            Achievement.CompleteCollectionGathering => AchievementCategory.Collection,
            Achievement.CompleteCollectionCrafting => AchievementCategory.Collection,
            Achievement.CompleteCollectionAlcohol => AchievementCategory.Collection,
            Achievement.CompleteCollectionCrop => AchievementCategory.Collection,
            Achievement.CompleteCollectionFish => AchievementCategory.Collection,
            Achievement.CompleteCollectionFood => AchievementCategory.Collection,
            Achievement.CompleteCollectionDrink => AchievementCategory.Collection,
            Achievement.MeetSummer => AchievementCategory.Event,
            _ => throw new ArgumentOutOfRangeException(nameof(achievement), achievement, null)
        };
    }
}
