using System;

namespace Hinode.Izumi.Data.Enums.AchievementEnums
{
    /// <summary>
    /// Достижение.
    /// </summary>
    public enum Achievement
    {
        FirstMessage = 1,
        FirstTransit = 2,
        FirstFish = 3,
        FirstGatheringResource = 4,
        FirstPlant = 5,
        FirstCraftResource = 6,
        FirstCraftAlcohol = 60,
        FirstCook = 7,
        FirstBet = 8,
        FirstJackPot = 9,
        FirstLotteryTicket = 10,
        FirstMarketDeal = 11,
        FirstContract = 20,
        FirstGiftSent = 23,
        FirstGiftReceived = 24,
        Gather40Resources = 21,
        Gather250Resources = 22,
        Catch50Fish = 12,
        Catch300Fish = 13,
        CatchEpicFish = 25,
        CatchMythicalFish = 26,
        CatchLegendaryFish = 27,
        CatchKoi = 28,
        Plant25Seed = 14,
        Plant150Seed = 15,
        Collect50Crop = 63,
        Collect300Crop = 64,
        Cook20Food = 18,
        Cook130Food = 19,
        Craft30Resource = 16,
        Craft250Resource = 17,
        Craft10Alcohol = 61,
        Craft80Alcohol = 62,
        Casino33Bet = 65,
        Casino777Bet = 66,
        Casino22LotteryBuy = 67,
        Casino99LotteryBuy = 68,
        Casino20LotteryGift = 69,
        Market100Sell = 70,
        Market666Sell = 71,
        Market50Buy = 72,
        Market333Buy = 73,
        Reach500ReputationCapital = 29,
        Reach500ReputationSeaport = 30,
        Reach500ReputationGarden = 31,
        Reach500ReputationCastle = 32,
        Reach500ReputationVillage = 33,
        Reach1000ReputationCapital = 34,
        Reach1000ReputationSeaport = 35,
        Reach1000ReputationGarden = 36,
        Reach1000ReputationCastle = 37,
        Reach1000ReputationVillage = 38,
        Reach2000ReputationCapital = 39,
        Reach2000ReputationSeaport = 40,
        Reach2000ReputationGarden = 41,
        Reach2000ReputationCastle = 42,
        Reach2000ReputationVillage = 43,
        Reach5000ReputationCapital = 44,
        Reach5000ReputationSeaport = 45,
        Reach5000ReputationGarden = 46,
        Reach5000ReputationCastle = 47,
        Reach5000ReputationVillage = 48,
        Reach10000ReputationCapital = 49,
        Reach10000ReputationSeaport = 50,
        Reach10000ReputationGarden = 51,
        Reach10000ReputationCastle = 52,
        Reach10000ReputationVillage = 53,
        CompleteCollectionGathering = 54,
        CompleteCollectionCrafting = 55,
        CompleteCollectionAlcohol = 56,
        CompleteCollectionCrop = 57,
        CompleteCollectionFish = 58,
        CompleteCollectionFood = 59,
        CompleteCollectionDrink = 74
    }

    public static class AchievementHelper
    {
        /// <summary>
        /// Возвращает локализированное название достижения.
        /// </summary>
        /// <param name="achievement">Достижение.</param>
        /// <returns></returns>
        public static string Localize(this Achievement achievement) => achievement switch
        {
            Achievement.FirstMessage => "Написать первое сообщение",
            Achievement.FirstTransit => "Впервые отправиться на транспорте",
            Achievement.FirstFish => "Выловить первую рыбу",
            Achievement.FirstGatheringResource => "Собрать свой первый ресурс",
            Achievement.FirstPlant => "Впервые посадить семена",
            Achievement.FirstCraftResource => "Впервые изготовить ресурс",
            Achievement.FirstCraftAlcohol => "Впервые изготовить алкоголь",
            Achievement.FirstCook => "Впервые приготовить блюдо",
            Achievement.FirstBet => "Впервые поставить монеты в казино",
            Achievement.FirstJackPot => "Впервые сорвать джек-пот в казино",
            Achievement.FirstLotteryTicket => "Купить свой первый лотерейный билет",
            Achievement.FirstMarketDeal => "Впервые купить или продать предмет на рынке",
            Achievement.FirstContract => "Выполнить свой первый рабочий контракт",
            Achievement.FirstGiftSent => "Впервые отправить подарок другому игроку",
            Achievement.FirstGiftReceived => "Впервые получить подарок от другого игрока",
            Achievement.Gather40Resources => "Собрать 40 ресурсов",
            Achievement.Gather250Resources => "Собрать 250 ресурсов",
            Achievement.Catch50Fish => "Выловить 50 рыб",
            Achievement.Catch300Fish => "Выловить 300 рыб",
            Achievement.CatchEpicFish => "Поймать эпическую рыбу",
            Achievement.CatchMythicalFish => "Поймать мифическую рыбу",
            Achievement.CatchLegendaryFish => "Поймать легендарную рыбу",
            Achievement.CatchKoi => "Выловить Кои",
            Achievement.Plant25Seed => "Посадить 25 семян",
            Achievement.Plant150Seed => "Посадить 150 семян",
            Achievement.Collect50Crop => "Собрать 50 урожая",
            Achievement.Collect300Crop => "Собрать 300 урожая",
            Achievement.Cook20Food => "Приготовить 20 блюд",
            Achievement.Cook130Food => "Приготовить 130 блюд",
            Achievement.Craft30Resource => "Изготовить 30 ресурсов",
            Achievement.Craft250Resource => "Изготовить 250 ресурсов",
            Achievement.Craft10Alcohol => "Изготовить 10 алкоголя",
            Achievement.Craft80Alcohol => "Изготовить 80 алкоголя",
            Achievement.Casino33Bet => "Сделать 33 ставки",
            Achievement.Casino777Bet => "Сделать 777 ставок",
            Achievement.Casino22LotteryBuy => "Купить 22 лотерейных билета",
            Achievement.Casino99LotteryBuy => "Купить 99 лотерейных билетов",
            Achievement.Casino20LotteryGift => "Подарить 20 лотерейных билетов",
            Achievement.Market100Sell => "Продать на рынке 100 предметов",
            Achievement.Market666Sell => "Продать на рынке 666 предметов",
            Achievement.Market50Buy => "Купить на рынке 50 предметов",
            Achievement.Market333Buy => "Купить на рынке 333 предмета",
            Achievement.Reach500ReputationCapital => "Достигнуть 500 репутации в столице",
            Achievement.Reach500ReputationSeaport => "Достигнуть 500 репутации в портовом городе",
            Achievement.Reach500ReputationGarden => "Достигнуть 500 репутации в цветущем саду",
            Achievement.Reach500ReputationCastle => "Достигнуть 500 репутации в древнем замке",
            Achievement.Reach500ReputationVillage => "Достигнуть 500 репутации в деревне",
            Achievement.Reach1000ReputationCapital => "Достигнуть 1000 репутации в столице",
            Achievement.Reach1000ReputationSeaport => "Достигнуть 1000 репутации в портовом городе",
            Achievement.Reach1000ReputationGarden => "Достигнуть 1000 репутации в цветущем саду",
            Achievement.Reach1000ReputationCastle => "Достигнуть 1000 репутации в древнем замке",
            Achievement.Reach1000ReputationVillage => "Достигнуть 1000 репутации в деревне",
            Achievement.Reach2000ReputationCapital => "Достигнуть 2000 репутации в столице",
            Achievement.Reach2000ReputationSeaport => "Достигнуть 2000 репутации в портовом городе",
            Achievement.Reach2000ReputationGarden => "Достигнуть 2000 репутации в цветущем саду",
            Achievement.Reach2000ReputationCastle => "Достигнуть 2000 репутации в древнем замке",
            Achievement.Reach2000ReputationVillage => "Достигнуть 2000 репутации в деревне",
            Achievement.Reach5000ReputationCapital => "Достигнуть 5000 репутации в столице",
            Achievement.Reach5000ReputationSeaport => "Достигнуть 5000 репутации в портовом городе",
            Achievement.Reach5000ReputationGarden => "Достигнуть 5000 репутации в цветущем саду",
            Achievement.Reach5000ReputationCastle => "Достигнуть 5000 репутации в древнем замке",
            Achievement.Reach5000ReputationVillage => "Достигнуть 5000 репутации в деревне",
            Achievement.Reach10000ReputationCapital => "Достигнуть 10000 репутации в столице",
            Achievement.Reach10000ReputationSeaport => "Достигнуть 10000 репутации в портовом городе",
            Achievement.Reach10000ReputationGarden => "Достигнуть 10000 репутации в цветущем саду",
            Achievement.Reach10000ReputationCastle => "Достигнуть 10000 репутации в древнем замке",
            Achievement.Reach10000ReputationVillage => "Достигнуть 10000 репутации в деревне",
            Achievement.CompleteCollectionGathering => "Собрать полную коллекцию ресурсов",
            Achievement.CompleteCollectionCrafting => "Собрать полную коллекцию изготовленных предметов",
            Achievement.CompleteCollectionAlcohol => "Собрать полную коллекцию алкоголя",
            Achievement.CompleteCollectionCrop => "Собрать полную коллекцию урожая",
            Achievement.CompleteCollectionFish => "Собрать полную коллекцию рыбы",
            Achievement.CompleteCollectionFood => "Собрать полную коллекцию блюд",
            Achievement.CompleteCollectionDrink => "Собрать полную коллекцию напитков",
            _ => throw new ArgumentOutOfRangeException(nameof(achievement), achievement, null)
        };

        /// <summary>
        /// Возвращает категорию в которой находится достижение.
        /// </summary>
        /// <param name="achievement">Достижение.</param>
        /// <returns>Категория в которой находится достижение.</returns>
        public static AchievementCategory Category(this Achievement achievement) => achievement switch
        {
            Achievement.FirstMessage => AchievementCategory.FirstSteps,
            Achievement.FirstTransit => AchievementCategory.FirstSteps,
            Achievement.FirstFish => AchievementCategory.FirstSteps,
            Achievement.FirstGatheringResource => AchievementCategory.FirstSteps,
            Achievement.FirstPlant => AchievementCategory.FirstSteps,
            Achievement.FirstCraftResource => AchievementCategory.FirstSteps,
            Achievement.FirstCraftAlcohol => AchievementCategory.FirstSteps,
            Achievement.FirstCook => AchievementCategory.FirstSteps,
            Achievement.FirstBet => AchievementCategory.FirstSteps,
            Achievement.FirstJackPot => AchievementCategory.FirstSteps,
            Achievement.FirstLotteryTicket => AchievementCategory.FirstSteps,
            Achievement.FirstMarketDeal => AchievementCategory.FirstSteps,
            Achievement.FirstContract => AchievementCategory.FirstSteps,
            Achievement.FirstGiftSent => AchievementCategory.FirstSteps,
            Achievement.FirstGiftReceived => AchievementCategory.FirstSteps,
            Achievement.Gather40Resources => AchievementCategory.Gathering,
            Achievement.Gather250Resources => AchievementCategory.Gathering,
            Achievement.Catch50Fish => AchievementCategory.Fishing,
            Achievement.Catch300Fish => AchievementCategory.Fishing,
            Achievement.CatchEpicFish => AchievementCategory.Fishing,
            Achievement.CatchMythicalFish => AchievementCategory.Fishing,
            Achievement.CatchLegendaryFish => AchievementCategory.Fishing,
            Achievement.CatchKoi => AchievementCategory.Fishing,
            Achievement.Plant25Seed => AchievementCategory.Harvesting,
            Achievement.Plant150Seed => AchievementCategory.Harvesting,
            Achievement.Collect50Crop => AchievementCategory.Harvesting,
            Achievement.Collect300Crop => AchievementCategory.Harvesting,
            Achievement.Cook20Food => AchievementCategory.Cooking,
            Achievement.Cook130Food => AchievementCategory.Cooking,
            Achievement.Craft30Resource => AchievementCategory.Crafting,
            Achievement.Craft250Resource => AchievementCategory.Crafting,
            Achievement.Craft10Alcohol => AchievementCategory.Crafting,
            Achievement.Craft80Alcohol => AchievementCategory.Crafting,
            Achievement.Casino33Bet => AchievementCategory.Casino,
            Achievement.Casino777Bet => AchievementCategory.Casino,
            Achievement.Casino22LotteryBuy => AchievementCategory.Casino,
            Achievement.Casino99LotteryBuy => AchievementCategory.Casino,
            Achievement.Casino20LotteryGift => AchievementCategory.Casino,
            Achievement.Market100Sell => AchievementCategory.Trading,
            Achievement.Market666Sell => AchievementCategory.Trading,
            Achievement.Market50Buy => AchievementCategory.Trading,
            Achievement.Market333Buy => AchievementCategory.Trading,
            Achievement.Reach500ReputationCapital => AchievementCategory.Reputation,
            Achievement.Reach500ReputationSeaport => AchievementCategory.Reputation,
            Achievement.Reach500ReputationGarden => AchievementCategory.Reputation,
            Achievement.Reach500ReputationCastle => AchievementCategory.Reputation,
            Achievement.Reach500ReputationVillage => AchievementCategory.Reputation,
            Achievement.Reach1000ReputationCapital => AchievementCategory.Reputation,
            Achievement.Reach1000ReputationSeaport => AchievementCategory.Reputation,
            Achievement.Reach1000ReputationGarden => AchievementCategory.Reputation,
            Achievement.Reach1000ReputationCastle => AchievementCategory.Reputation,
            Achievement.Reach1000ReputationVillage => AchievementCategory.Reputation,
            Achievement.Reach2000ReputationCapital => AchievementCategory.Reputation,
            Achievement.Reach2000ReputationSeaport => AchievementCategory.Reputation,
            Achievement.Reach2000ReputationGarden => AchievementCategory.Reputation,
            Achievement.Reach2000ReputationCastle => AchievementCategory.Reputation,
            Achievement.Reach2000ReputationVillage => AchievementCategory.Reputation,
            Achievement.Reach5000ReputationCapital => AchievementCategory.Reputation,
            Achievement.Reach5000ReputationSeaport => AchievementCategory.Reputation,
            Achievement.Reach5000ReputationGarden => AchievementCategory.Reputation,
            Achievement.Reach5000ReputationCastle => AchievementCategory.Reputation,
            Achievement.Reach5000ReputationVillage => AchievementCategory.Reputation,
            Achievement.Reach10000ReputationCapital => AchievementCategory.Reputation,
            Achievement.Reach10000ReputationSeaport => AchievementCategory.Reputation,
            Achievement.Reach10000ReputationGarden => AchievementCategory.Reputation,
            Achievement.Reach10000ReputationCastle => AchievementCategory.Reputation,
            Achievement.Reach10000ReputationVillage => AchievementCategory.Reputation,
            Achievement.CompleteCollectionGathering => AchievementCategory.Collection,
            Achievement.CompleteCollectionCrafting => AchievementCategory.Collection,
            Achievement.CompleteCollectionAlcohol => AchievementCategory.Collection,
            Achievement.CompleteCollectionCrop => AchievementCategory.Collection,
            Achievement.CompleteCollectionFish => AchievementCategory.Collection,
            Achievement.CompleteCollectionFood => AchievementCategory.Collection,
            Achievement.CompleteCollectionDrink => AchievementCategory.Collection,
            _ => throw new ArgumentOutOfRangeException(nameof(achievement), achievement, null)
        };
    }
}
